version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-wsb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wsbuser
      POSTGRES_PASSWORD: wsbpass
      POSTGRES_DB: wsb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
